/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface Location {
    id: string;
    taluk: string;
    officeName: string;
    district: string;
    village: string;
}
export interface DocumentPreparer {
    id: string;
    name: string;
    office: string;
    mobile: string;
}
export interface DeedDraft {
    id: string;
    createdAt: bigint;
    formData: string;
    updatedAt: bigint;
    deedType: DeedType;
}
export interface Party {
    id: string;
    relationship: string;
    name: string;
    aadhaar: string;
    address: string;
    mobile: string;
}
export enum DeedType {
    AgreementDeed = "AgreementDeed",
    SaleDeed = "SaleDeed"
}
export interface backendInterface {
    addLocation(location: Location): Promise<void>;
    addParty(party: Party): Promise<void>;
    addPreparer(preparer: DocumentPreparer): Promise<void>;
    deleteDraft(id: string): Promise<void>;
    deleteLocation(id: string): Promise<void>;
    deleteParty(id: string): Promise<void>;
    deletePreparer(id: string): Promise<void>;
    getAllDrafts(): Promise<Array<DeedDraft>>;
    getAllLocations(): Promise<Array<Location>>;
    getAllParties(): Promise<Array<Party>>;
    getAllPreparers(): Promise<Array<DocumentPreparer>>;
    getDraft(id: string): Promise<DeedDraft | null>;
    getLocation(id: string): Promise<Location | null>;
    getParty(id: string): Promise<Party | null>;
    getPreparer(id: string): Promise<DocumentPreparer | null>;
    saveDraft(draft: DeedDraft): Promise<void>;
    updateDraft(draft: DeedDraft): Promise<void>;
    updateLocation(location: Location): Promise<void>;
    updateParty(party: Party): Promise<void>;
    updatePreparer(preparer: DocumentPreparer): Promise<void>;
}
import type { DeedDraft as _DeedDraft, DeedType as _DeedType, DocumentPreparer as _DocumentPreparer, Location as _Location, Party as _Party } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async addLocation(arg0: Location): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addLocation(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addLocation(arg0);
            return result;
        }
    }
    async addParty(arg0: Party): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addParty(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addParty(arg0);
            return result;
        }
    }
    async addPreparer(arg0: DocumentPreparer): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addPreparer(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addPreparer(arg0);
            return result;
        }
    }
    async deleteDraft(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteDraft(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteDraft(arg0);
            return result;
        }
    }
    async deleteLocation(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteLocation(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteLocation(arg0);
            return result;
        }
    }
    async deleteParty(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteParty(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteParty(arg0);
            return result;
        }
    }
    async deletePreparer(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deletePreparer(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deletePreparer(arg0);
            return result;
        }
    }
    async getAllDrafts(): Promise<Array<DeedDraft>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllDrafts();
                return from_candid_vec_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllDrafts();
            return from_candid_vec_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllLocations(): Promise<Array<Location>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllLocations();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllLocations();
            return result;
        }
    }
    async getAllParties(): Promise<Array<Party>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllParties();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllParties();
            return result;
        }
    }
    async getAllPreparers(): Promise<Array<DocumentPreparer>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllPreparers();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllPreparers();
            return result;
        }
    }
    async getDraft(arg0: string): Promise<DeedDraft | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getDraft(arg0);
                return from_candid_opt_n6(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getDraft(arg0);
            return from_candid_opt_n6(this._uploadFile, this._downloadFile, result);
        }
    }
    async getLocation(arg0: string): Promise<Location | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getLocation(arg0);
                return from_candid_opt_n7(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getLocation(arg0);
            return from_candid_opt_n7(this._uploadFile, this._downloadFile, result);
        }
    }
    async getParty(arg0: string): Promise<Party | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getParty(arg0);
                return from_candid_opt_n8(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getParty(arg0);
            return from_candid_opt_n8(this._uploadFile, this._downloadFile, result);
        }
    }
    async getPreparer(arg0: string): Promise<DocumentPreparer | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getPreparer(arg0);
                return from_candid_opt_n9(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPreparer(arg0);
            return from_candid_opt_n9(this._uploadFile, this._downloadFile, result);
        }
    }
    async saveDraft(arg0: DeedDraft): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveDraft(to_candid_DeedDraft_n10(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveDraft(to_candid_DeedDraft_n10(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async updateDraft(arg0: DeedDraft): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateDraft(to_candid_DeedDraft_n10(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateDraft(to_candid_DeedDraft_n10(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async updateLocation(arg0: Location): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateLocation(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateLocation(arg0);
            return result;
        }
    }
    async updateParty(arg0: Party): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateParty(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateParty(arg0);
            return result;
        }
    }
    async updatePreparer(arg0: DocumentPreparer): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updatePreparer(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updatePreparer(arg0);
            return result;
        }
    }
}
function from_candid_DeedDraft_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _DeedDraft): DeedDraft {
    return from_candid_record_n3(_uploadFile, _downloadFile, value);
}
function from_candid_DeedType_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _DeedType): DeedType {
    return from_candid_variant_n5(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_DeedDraft]): DeedDraft | null {
    return value.length === 0 ? null : from_candid_DeedDraft_n2(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Location]): Location | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Party]): Party | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_DocumentPreparer]): DocumentPreparer | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    createdAt: bigint;
    formData: string;
    updatedAt: bigint;
    deedType: _DeedType;
}): {
    id: string;
    createdAt: bigint;
    formData: string;
    updatedAt: bigint;
    deedType: DeedType;
} {
    return {
        id: value.id,
        createdAt: value.createdAt,
        formData: value.formData,
        updatedAt: value.updatedAt,
        deedType: from_candid_DeedType_n4(_uploadFile, _downloadFile, value.deedType)
    };
}
function from_candid_variant_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    AgreementDeed: null;
} | {
    SaleDeed: null;
}): DeedType {
    return "AgreementDeed" in value ? DeedType.AgreementDeed : "SaleDeed" in value ? DeedType.SaleDeed : value;
}
function from_candid_vec_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_DeedDraft>): Array<DeedDraft> {
    return value.map((x)=>from_candid_DeedDraft_n2(_uploadFile, _downloadFile, x));
}
function to_candid_DeedDraft_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: DeedDraft): _DeedDraft {
    return to_candid_record_n11(_uploadFile, _downloadFile, value);
}
function to_candid_DeedType_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: DeedType): _DeedType {
    return to_candid_variant_n13(_uploadFile, _downloadFile, value);
}
function to_candid_record_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    createdAt: bigint;
    formData: string;
    updatedAt: bigint;
    deedType: DeedType;
}): {
    id: string;
    createdAt: bigint;
    formData: string;
    updatedAt: bigint;
    deedType: _DeedType;
} {
    return {
        id: value.id,
        createdAt: value.createdAt,
        formData: value.formData,
        updatedAt: value.updatedAt,
        deedType: to_candid_DeedType_n12(_uploadFile, _downloadFile, value.deedType)
    };
}
function to_candid_variant_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: DeedType): {
    AgreementDeed: null;
} | {
    SaleDeed: null;
} {
    return value == DeedType.AgreementDeed ? {
        AgreementDeed: null
    } : value == DeedType.SaleDeed ? {
        SaleDeed: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
