/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Location = IDL.Record({
  'id' : IDL.Text,
  'taluk' : IDL.Text,
  'officeName' : IDL.Text,
  'district' : IDL.Text,
  'village' : IDL.Text,
});
export const Party = IDL.Record({
  'id' : IDL.Text,
  'relationship' : IDL.Text,
  'name' : IDL.Text,
  'aadhaar' : IDL.Text,
  'address' : IDL.Text,
  'mobile' : IDL.Text,
});
export const DocumentPreparer = IDL.Record({
  'id' : IDL.Text,
  'name' : IDL.Text,
  'office' : IDL.Text,
  'mobile' : IDL.Text,
});
export const DeedType = IDL.Variant({
  'AgreementDeed' : IDL.Null,
  'SaleDeed' : IDL.Null,
});
export const DeedDraft = IDL.Record({
  'id' : IDL.Text,
  'createdAt' : IDL.Int,
  'formData' : IDL.Text,
  'updatedAt' : IDL.Int,
  'deedType' : DeedType,
});

export const idlService = IDL.Service({
  'addLocation' : IDL.Func([Location], [], []),
  'addParty' : IDL.Func([Party], [], []),
  'addPreparer' : IDL.Func([DocumentPreparer], [], []),
  'deleteDraft' : IDL.Func([IDL.Text], [], []),
  'deleteLocation' : IDL.Func([IDL.Text], [], []),
  'deleteParty' : IDL.Func([IDL.Text], [], []),
  'deletePreparer' : IDL.Func([IDL.Text], [], []),
  'getAllDrafts' : IDL.Func([], [IDL.Vec(DeedDraft)], ['query']),
  'getAllLocations' : IDL.Func([], [IDL.Vec(Location)], ['query']),
  'getAllParties' : IDL.Func([], [IDL.Vec(Party)], ['query']),
  'getAllPreparers' : IDL.Func([], [IDL.Vec(DocumentPreparer)], ['query']),
  'getDraft' : IDL.Func([IDL.Text], [IDL.Opt(DeedDraft)], ['query']),
  'getLocation' : IDL.Func([IDL.Text], [IDL.Opt(Location)], ['query']),
  'getParty' : IDL.Func([IDL.Text], [IDL.Opt(Party)], ['query']),
  'getPreparer' : IDL.Func([IDL.Text], [IDL.Opt(DocumentPreparer)], ['query']),
  'saveDraft' : IDL.Func([DeedDraft], [], []),
  'updateDraft' : IDL.Func([DeedDraft], [], []),
  'updateLocation' : IDL.Func([Location], [], []),
  'updateParty' : IDL.Func([Party], [], []),
  'updatePreparer' : IDL.Func([DocumentPreparer], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Location = IDL.Record({
    'id' : IDL.Text,
    'taluk' : IDL.Text,
    'officeName' : IDL.Text,
    'district' : IDL.Text,
    'village' : IDL.Text,
  });
  const Party = IDL.Record({
    'id' : IDL.Text,
    'relationship' : IDL.Text,
    'name' : IDL.Text,
    'aadhaar' : IDL.Text,
    'address' : IDL.Text,
    'mobile' : IDL.Text,
  });
  const DocumentPreparer = IDL.Record({
    'id' : IDL.Text,
    'name' : IDL.Text,
    'office' : IDL.Text,
    'mobile' : IDL.Text,
  });
  const DeedType = IDL.Variant({
    'AgreementDeed' : IDL.Null,
    'SaleDeed' : IDL.Null,
  });
  const DeedDraft = IDL.Record({
    'id' : IDL.Text,
    'createdAt' : IDL.Int,
    'formData' : IDL.Text,
    'updatedAt' : IDL.Int,
    'deedType' : DeedType,
  });
  
  return IDL.Service({
    'addLocation' : IDL.Func([Location], [], []),
    'addParty' : IDL.Func([Party], [], []),
    'addPreparer' : IDL.Func([DocumentPreparer], [], []),
    'deleteDraft' : IDL.Func([IDL.Text], [], []),
    'deleteLocation' : IDL.Func([IDL.Text], [], []),
    'deleteParty' : IDL.Func([IDL.Text], [], []),
    'deletePreparer' : IDL.Func([IDL.Text], [], []),
    'getAllDrafts' : IDL.Func([], [IDL.Vec(DeedDraft)], ['query']),
    'getAllLocations' : IDL.Func([], [IDL.Vec(Location)], ['query']),
    'getAllParties' : IDL.Func([], [IDL.Vec(Party)], ['query']),
    'getAllPreparers' : IDL.Func([], [IDL.Vec(DocumentPreparer)], ['query']),
    'getDraft' : IDL.Func([IDL.Text], [IDL.Opt(DeedDraft)], ['query']),
    'getLocation' : IDL.Func([IDL.Text], [IDL.Opt(Location)], ['query']),
    'getParty' : IDL.Func([IDL.Text], [IDL.Opt(Party)], ['query']),
    'getPreparer' : IDL.Func(
        [IDL.Text],
        [IDL.Opt(DocumentPreparer)],
        ['query'],
      ),
    'saveDraft' : IDL.Func([DeedDraft], [], []),
    'updateDraft' : IDL.Func([DeedDraft], [], []),
    'updateLocation' : IDL.Func([Location], [], []),
    'updateParty' : IDL.Func([Party], [], []),
    'updatePreparer' : IDL.Func([DocumentPreparer], [], []),
  });
};

export const init = ({ IDL }) => { return []; };