/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface DeedDraft {
  'id' : string,
  'createdAt' : bigint,
  'formData' : string,
  'updatedAt' : bigint,
  'deedType' : DeedType,
}
export type DeedType = { 'AgreementDeed' : null } |
  { 'SaleDeed' : null };
export interface DocumentPreparer {
  'id' : string,
  'name' : string,
  'office' : string,
  'mobile' : string,
}
export interface Location {
  'id' : string,
  'taluk' : string,
  'officeName' : string,
  'district' : string,
  'village' : string,
}
export interface Party {
  'id' : string,
  'relationship' : string,
  'name' : string,
  'aadhaar' : string,
  'address' : string,
  'mobile' : string,
}
export interface _SERVICE {
  'addLocation' : ActorMethod<[Location], undefined>,
  'addParty' : ActorMethod<[Party], undefined>,
  'addPreparer' : ActorMethod<[DocumentPreparer], undefined>,
  'deleteDraft' : ActorMethod<[string], undefined>,
  'deleteLocation' : ActorMethod<[string], undefined>,
  'deleteParty' : ActorMethod<[string], undefined>,
  'deletePreparer' : ActorMethod<[string], undefined>,
  'getAllDrafts' : ActorMethod<[], Array<DeedDraft>>,
  'getAllLocations' : ActorMethod<[], Array<Location>>,
  'getAllParties' : ActorMethod<[], Array<Party>>,
  'getAllPreparers' : ActorMethod<[], Array<DocumentPreparer>>,
  'getDraft' : ActorMethod<[string], [] | [DeedDraft]>,
  'getLocation' : ActorMethod<[string], [] | [Location]>,
  'getParty' : ActorMethod<[string], [] | [Party]>,
  'getPreparer' : ActorMethod<[string], [] | [DocumentPreparer]>,
  'saveDraft' : ActorMethod<[DeedDraft], undefined>,
  'updateDraft' : ActorMethod<[DeedDraft], undefined>,
  'updateLocation' : ActorMethod<[Location], undefined>,
  'updateParty' : ActorMethod<[Party], undefined>,
  'updatePreparer' : ActorMethod<[DocumentPreparer], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];